## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  DBT-DEMO:
    staging:
      +materialized: view
      +schema: salesforce
    marts:
      +materialized: table
