tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'TAIZQZT-QP81056'
      user: 'johndotnet21'
      password: 'India@1234567890'
      role: accountadmin
      database: edw_dev_stg
      schema: salesforce
      warehouse: compute_wh
    prod:
      type: snowflake
      account: 'TAIZQZT-QP81056'
      user: 'johndotnet21'
      password: 'India@1234567890'
      role: accountadmin
      database: edw_dev_stg
      schema: dev
      warehouse: compute_wh